import Head from 'next/head'
import Header from '../components/Header'
import Slider from '../components/Slider';
import ProductFeed from '../components/ProductFeed';

export default function Home({ products }) {
  return (
    <div className="bg-gray-100" >
      <Head>
        <title>Mustache Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Slider />
      </main>
      
      {/* Product */}
      <ProductFeed products={products} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then((res) => res.json()
  );

  return {
     props: {
      products ,
  } }
}

// GET >> https://fakestoreapi.com/products