import Head from 'next/head'
import Header from '../components/Header'
import Slider from '../components/Slider';

export default function Home() {
  return (
    <div className="bg-gray-100" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Slider />
      </main>
      
      
      {/* Product */}
    </div>
  )
}
